-- Phase 2 test 13: BEGIN/ROLLBACK — exercises hton->rollback.
CREATE TABLE t1 (id INT PRIMARY KEY, v VARCHAR(32)) ENGINE=TIDESDB;
INSERT INTO t1 VALUES (1,'a');
START TRANSACTION;
INSERT INTO t1 VALUES (2,'b'),(3,'c');
ROLLBACK;
SELECT id, v FROM t1 ORDER BY id;
SELECT COUNT(*) AS visible FROM t1;
DROP TABLE t1;
